[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.24"        # Para renderização gráfica
cpal = "0.15"          # Para áudio
bincode = "1.3"        # Para save states
rand = "0.8"           # Para números aleatórios